import { AGENTICGRAPH_AGENT_READY_TOOL_IDS } from "./agenticgraphAgentReadyToolContract.mjs";
import { AGENTICGRAPH_PROBE_TREE_TOOL_NAMES } from "./probeTreeContract.mjs";
import { AGENTICGRAPH_STORAGE_LOCAL_TOOL_NAMES } from "../../lib/storage/agenticgraphStorageEngineMcpContract.mjs";

export const AGENTICGRAPH_OS_STATUS_TOOL_NAME = "agenticgraph.os.status";

export const AGENTICGRAPH_LOCAL_MCP_TOOL_NAMES = Object.freeze({
  search: AGENTICGRAPH_AGENT_READY_TOOL_IDS.search,
  fetch: AGENTICGRAPH_AGENT_READY_TOOL_IDS.fetch,
  uiLaunch: "agenticgraph.ui.launch",
  uiStop: "agenticgraph.ui.stop",
  geospatialCommand: "agenticgraph.geospatial.command",
  pipeline: "agenticgraph.pipeline",
  graphragPipeline: "agenticgraph.graphrag_pipeline",
  knowledgeGraphParserGenerate: "agenticgraph.knowledge_graph.parser_generate",
  knowledgeGraphIngest: "agenticgraph.knowledge_graph.ingest",
  knowledgeGraphQuery: "agenticgraph.knowledge_graph.query",
  knowledgeGraphExplainEdge: "agenticgraph.knowledge_graph.explain_edge",
  superagentRun: "agenticgraph.superagent.run",
  videoRemixRun: "agenticgraph.video_remix.run",
  browserApiRun: "agenticgraph.browser_api.run",
  gitRun: AGENTICGRAPH_STORAGE_LOCAL_TOOL_NAMES.gitRun,
  fileSyncRun: AGENTICGRAPH_STORAGE_LOCAL_TOOL_NAMES.fileSyncRun,
  sealionDetectLanguageVariant: "sealion.detect_language_variant",
  sealionTranslateLocalize: "sealion.translate_localize",
  sealionSafetyCheck: "sealion.safety_check",
  htmlVideoRender: "agenticgraph.html_video.render",
  annotateImage: "agenticgraph.annotate.image",
  annotateVideoFrame: "agenticgraph.annotate.video_frame",
  memoryAdd: "agenticgraph.memory.add",
  memoryWrite: "agenticgraph.memory.write",
  memoryCompact: "agenticgraph.memory.compact",
  memorySearch: "agenticgraph.memory.search",
  sessionSearch: "agenticgraph.session.search",
  userProfile: "agenticgraph.user.profile",
  memoryInvoke: "agenticgraph.memory.invoke",
  memoryAssemblePrompt: "agenticgraph.memory.assemble_prompt",
  memoryExtractProcedural: "agenticgraph.memory.extract_procedural",
  memoryMaterializeUserModel: "agenticgraph.memory.materialize_user_model",
  probeGenerate: AGENTICGRAPH_PROBE_TREE_TOOL_NAMES.generate,
  probeSelect: AGENTICGRAPH_PROBE_TREE_TOOL_NAMES.select,
  probeEvolve: AGENTICGRAPH_PROBE_TREE_TOOL_NAMES.evolve,
  smeSourceNormalize: "agenticgraph.sme.source.normalize",
  smeTriggerEvaluate: "agenticgraph.sme.trigger.evaluate",
  smeBrokerDraftNudge: "agenticgraph.sme.broker.draft_nudge",
  smeMarketplaceMatch: "agenticgraph.sme.marketplace.match",
  smeMultilingualAdapt: "agenticgraph.sme.multilingual.adapt",
  smeCareAgentStatus: "sme_care_agent_status",
  agenticCanvasOsDocsInvoke: "agenticgraph.agentic_canvas_os.docs.invoke",
  skillEvolve: "agenticgraph.skill.evolve",
  repositoryPack: "agenticgraph.repository.pack",
  workspaceArtifactPlan: "agenticgraph.workspace_artifact.plan",
  workspaceArtifactApply: "agenticgraph.workspace_artifact.apply",
  implementationRunPlan: "agenticgraph.implementation_run.plan",
  implementationRunStart: "agenticgraph.implementation_run.start",
  implementationRunList: "agenticgraph.implementation_run.list",
  implementationRunControl: "agenticgraph.implementation_run.control",
  agenticSdlcObserve: "agenticgraph.agentic_sdlc.observe",
  agentTeamPlan: "agenticgraph.agent_team.plan",
  agentTeamStart: "agenticgraph.agent_team.start",
  agentTeamList: "agenticgraph.agent_team.list",
  agentTeamControl: "agenticgraph.agent_team.control",
  exportPublish: "export.publish",
  toolCatalog: "agenticgraph.tool.catalog",
  toolSearch: "agenticgraph.tool.search",
  toolDescribe: "agenticgraph.tool.describe",
  toolCall: "agenticgraph.tool.call",
  showrunnerStartRun: "agenticgraph.showrunner.start_run",
  showrunnerRunStatus: "agenticgraph.showrunner.run_status",
  showrunnerPostChoice: "agenticgraph.showrunner.post_choice",
  showrunnerSubmitCritique: "agenticgraph.showrunner.submit_critique",
  showrunnerApproveStage: "agenticgraph.showrunner.approve_stage",
  showrunnerGetArtifact: "agenticgraph.showrunner.get_artifact",
  sandboxPolicyValidate: "agenticgraph.sandbox.policy.validate",
  sandboxPolicyAuthorize: "agenticgraph.sandbox.policy.authorize",
  ecsSessionStart: "agenticgraph.ecs.session_start",
  ecsWorldTick: "agenticgraph.ecs.world_tick",
  ecsDecisionPersist: "agenticgraph.ecs.decision_persist",
  paymentRailSelect: "agenticgraph.payment.rail.select",
  paymentIntentCreate: "agenticgraph.payment.intent.create",
  paymentStatus: "agenticgraph.payment.status",
  paymentEventSettle: "agenticgraph.payment.event.settle",
  paymentReconcile: "agenticgraph.payment.reconcile",
  paymentReceiptProject: "agenticgraph.payment.receipt.project",
  paymentRefund: "agenticgraph.payment.refund",
  paymentReadiness: "agenticgraph.payment.readiness",
  osStatus: AGENTICGRAPH_OS_STATUS_TOOL_NAME,
  vdeoxplnList: "agenticgraph.vdeoxpln.list",
  applicationCatalog: "agenticgraph.application.catalog",
  applicationPlan: "agenticgraph.application.plan",
  applicationExecute: "agenticgraph.application.execute",
  voiceStudio: "agenticgraph.voice.studio",
});

export const buildAgenticGraphLocalMcpToolNameList = () => Object.values(AGENTICGRAPH_LOCAL_MCP_TOOL_NAMES);
